import { PGlite } from '@electric-sql/pglite';
import { drizzle } from 'drizzle-orm/pglite';
import { migrate } from 'drizzle-orm/pglite/migrator';
import { eq } from 'drizzle-orm';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as schema from './schema';

/**
 * Dev/test database is PGlite — Postgres compiled to WASM. No native build, no
 * separate server, and the SAME dialect as prod Postgres. `DATABASE_URL` may
 * be a directory path (persistent) or `memory://` (ephemeral, used by tests).
 */
const DATA_DIR = process.env.DATABASE_URL ?? './kestrel-pgdata';

const client = new PGlite(DATA_DIR);
export const db = drizzle(client, { schema });

// v1 is single-host: seed a default account so ingest has a tenant to attach
// hosts to. The data model stays multi-tenant; this is just the dev default.
export const DEFAULT_ACCOUNT_ID = '00000000-0000-0000-0000-000000000001';

async function ensureDefaultAccount(): Promise<void> {
	const existing = await db
		.select({ id: schema.accounts.id })
		.from(schema.accounts)
		.where(eq(schema.accounts.id, DEFAULT_ACCOUNT_ID));
	if (existing.length === 0) {
		await db
			.insert(schema.accounts)
			.values({ id: DEFAULT_ACCOUNT_ID, name: 'default' })
			.onConflictDoNothing();
	}
}

const migrationsFolder = fileURLToPath(new URL('../../../../drizzle', import.meta.url));

/**
 * Idempotent startup: apply migrations (generated by `pnpm drizzle:generate`)
 * and seed the default account. Every DB caller must `await dbReady` first.
 */
export const dbReady: Promise<void> = (async () => {
	if (existsSync(migrationsFolder)) {
		await migrate(db, { migrationsFolder });
	}
	await ensureDefaultAccount();
})();

export { schema };
